In [1]:
import numpy as np
import matplotlib.pyplot as plt

import copy

# 100 практических задач с python
<p>Курс "Модели и методы интеллектуального анализа данных"</p>
<p>Чернышов Юрий</p>
<p>к.ф.-м.н., доцент кафедры ИТЗИ УрГУПС (Екатеринбург)</p>
<p>yuchernyshov@usurt.ru</p>

# Оглавление <a name='toc'>
    
<ol>
<li><a href='#intro'>Введение</a></li>
<li><a href='#101'>10 простых алгоритмов</a></li>
<li><a href='#sort'>Сортировка</a></li>
<li><a href='#ML'>Машинное обучение</a></li>
<li><a href='#genetics'>Генетические алгоритмы</a></li>
<li><a href='#links'>Ссылки</a></li>
</ol>


# Введение <a name='intro'></a>

Язык Python был создан в 1991 году. В настоящее время интерес к использованию Python возрос в связи с большим количеством разработанных специализированных библиотек для отдельных задач, многочисленным сообществом разработчиков, а также применением Python для важных практических задач: математического моделирования, научных исследований, обработки данных и пр. Python является одним из основных инструментов при решении задач машинного обучения.

Python - интерпретируемый язык программирования. Программа Python (также используется термин скрипт) состоит из команд, которые последовательно выполняются интерптетатором Python.

Python проигрывает в скорости выполнения программ компилируемым языкам программирования (например, C), но имеет ряд преимуществ - наглядность, простота, лаконичность, популярность. Для быстрого предварительного исследования, моделирования, проверки гипотез, визуализации использование Python предпочтительнее.

Документ состоит из 100 сложных задач, решаемых с помощью Python и соответствующих библиотек.

Для удобства задачи разбиты на группы, к которым можно быстро перейти через <a href='#toc'>Оглавление</a>.

<a href='#toc'>Назад к Оглавлению</a>

# 10 простых алгоритмов <a name='101'></a>

<a href='#toc'>Назад к Оглавлению</a>

# Сортировка <a name='sort'></a>

#### Пузырьковая сортировка

#### Сортировка выбором

#### Пирамидальная сортировка

<a href='#toc'>Назад к Оглавлению</a>

# Алгоритмы оптимизации <a name='optimization'></a>

#### Венгерский алгоритм

#### Задача об укладке рюкзака

#### Транспортная задача

#### Задача коммивояжера

<a href='#toc'>Назад к Оглавлению</a>

# Машинное обучение <a name='ML'></a>

<a href='#toc'>Назад к Оглавлению</a>

# Генетические алгоритмы <a name='genetics'></a>

#### Создать алгоритм, который находит строку заданной длины, имеющей максимальную сумму цифр строки.

In [2]:
# длина строки
l = 1000

# размер популяции
n = 1000

population = np.array([[np.random.choice([0, 1]) for i in range(l)] for j in range(n)])

In [3]:
population.shape

(1000, 1000)

In [4]:
class Population():
    
    def __init__(self, length, size):
        self.length = length
        self.size = size
        self.population = np.array([[np.random.choice([0, 1]) for i in range(length)] for j in range(size)])
        
    def choice(self):
        pass

    def cross(self):
        pass
    
    def cross(self):
        pass

    def mutation(self):
        pass
    
    def __str__(self):
        return "Class Population"

In [57]:
def selection(s):
    tmp = []
    m = 0
    for i in range(s.shape[0]):
        m += np.sum(s[i,:])
    m /= s.shape[0]
    for i in range(s.shape[0]):
        if np.sum(s[i,:]) >= m:
            tmp.append(s[i,:])
    return np.array(tmp)
        

In [58]:
result = copy.deepcopy(population)

In [59]:
%%time

for _ in range(100):
    result = selection(result)


CPU times: user 1.52 s, sys: 8.02 ms, total: 1.52 s
Wall time: 1.52 s


In [60]:
print(result.shape)

(1, 1000)


In [53]:
sorted(population, key=lambda x: np.sum(x), reverse=True)[:5]

[array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])]

<a href='#toc'>Назад к Оглавлению</a>

# Ссылки <a name='links'></a>

http://www.matplotlib.org - официальная страница проекта matplotlib.

https://colab.research.google.com/ - интерактивная среда для программирования на python

<a href='#toc'>Назад к Оглавлению</a>