In [52]:
import numpy as np
import matplotlib.pyplot as plt

from scipy.stats import norm

# Генетические алгоритмы

<p>Курс "Модели и методы интеллектуального анализа данных"</p>
<p>Чернышов Юрий</p>
<p>к.ф.-м.н., доцент кафедры ИТЗИ УрГУПС (Екатеринбург)</p>
<p>yuchernyshov@usurt.ru</p>

# Оглавление <a name='toc'>
    
<ol>
<li><a href='#intro'>Введение</a></li>
<li><a href='#links'>Ссылки</a></li>
</ol>


# Введение <a name='intro'></a>

Генетические алгоритмы позволяют решать задачи оптимизации, используя эволючионные механизмы.

Отбор, скрещивание, мутация.

Элитизм, выбор ниш.

Гиперпараметры.

Стандартные библиотеки deap.

При невозможности установки python и matplotlib для практической работы можно воспользоваться ресурсом "Google colab" https://colab.research.google.com/

Для удобства задачи разбиты на группы, к которым можно быстро перейти в <a href='#toc'>Оглавлении</a>.

<a href='#toc'>Назад к Оглавлению</a>

# Работа с библиотекой DEAP <a name='deap'></a>

In [24]:
from deap import creator, base

In [17]:
class Person():
    
    def __init__(self, name='noname'):
        self.name = name
        
    def __str__(self):
        return("class Person, name: {}".format(self.name))
    

In [18]:
creator.create("Developer", Person, position = "Developer", programming_lang = set)

In [21]:
dev1 = creator.Developer("Steve")

In [22]:
print(dev1)

class Person, name: Steve


In [25]:
creator.create("FitnessMax", base.Fitness, weights=(1.0,))

In [34]:
creator.FitnessMax.values, creator.FitnessMax.wvalues

(<property at 0x7fc4057863b0>, ())

In [37]:
creator.create("Individual", list, fitness=creator.FitnessMax)

In [39]:
creator.Individual

deap.creator.Individual

In [40]:
toolbox = base.Toolbox()

In [41]:
def f(name='noname', occupation='none'):
    print("My name is {}, I am a {}".format(name, occupation))

In [45]:
toolbox.register("f_Ivan", f, name='Ivan')
toolbox.register("f_Developer", f, occupation='Developer')

In [46]:
toolbox.f_Ivan()
toolbox.f_Developer()

My name is Ivan, I am a none
My name is noname, I am a Developer


In [47]:
from deap import tools

In [48]:
toolbox.register("select", tools.selRoulette)

In [49]:
toolbox.register("mate", tools.cxOnePoint)

In [50]:
toolbox.register("mutate", tools.mutFlipBit)

In [68]:
toolbox.register("get_val", np.random.choice, [0,1], 10)

randomList = tools.initRepeat(list, toolbox.get_val, 10)

In [70]:
randomList

[array([0, 1, 1, 1, 1, 1, 1, 0, 1, 0]),
 array([0, 1, 0, 1, 1, 1, 1, 0, 0, 1]),
 array([0, 1, 1, 1, 1, 1, 1, 1, 0, 0]),
 array([0, 0, 0, 1, 1, 1, 0, 1, 0, 1]),
 array([0, 1, 1, 0, 1, 1, 0, 1, 0, 0]),
 array([0, 0, 0, 1, 1, 0, 0, 1, 0, 0]),
 array([1, 1, 0, 1, 1, 1, 0, 1, 0, 0]),
 array([1, 1, 0, 1, 1, 0, 0, 1, 0, 1]),
 array([0, 0, 0, 0, 1, 0, 1, 0, 0, 1]),
 array([0, 1, 1, 0, 1, 1, 1, 1, 0, 1])]

In [72]:
def calcFitnessValue(individual):
    return(np.sum(individial))

toolbox.register("evaluate", calcFitnessValue)

<a href='#toc'>Назад к Оглавлению</a>

# Ссылки <a name='links'></a>

https://colab.research.google.com/ - интерактивная среда для программирования на python

<a href='#toc'>Назад к Оглавлению</a>